export const typography = {
    'button': {
        textTransform: 'none',
    },
    'fontFamily': 'Poppins,Canela-Black,Roboto,Arial,sans-serif',
    'display1': {
        'fontFamily': 'Canela-Black',
        'fontSize': '3.8125rem',
        'fontStyle': 'normal',
        'fontWeight': 900,
        'lineHeight': 'normal',
        '@media screen and (max-width:1024px)': {
            fontSize: '3rem',
            lineHeight: '3.6rem',
        },
    },
    'display2': {
        'fontFamily': 'Canela-Black',
        'fontSize': '3.0625rem',
        'fontStyle': 'normal',
        'fontWeight': 900,
        'lineHeight': 'normal',
        '@media screen and (max-width:1024px)': {
            fontSize: '2.5rem',
            lineHeight: '3rem',
        },
    },
    'title1': {
        'fontFamily': 'Poppins',
        'fontSize': '2.4375rem',
        'fontStyle': 'normal',
        'fontWeight': 400,
        'lineHeight': 'normal',
        '@media screen and (max-width:1024px)': {
            fontSize: '2.0625rem',
            lineHeight: '2.475rem',
        },
    },
    'title2': {
        'fontFamily': 'Poppins',
        'fontSize': '1.9375rem',
        'fontStyle': 'normal',
        'fontWeight': 400,
        'lineHeight': 'normal',
        '@media screen and (max-width:1024px)': {
            fontSize: '1.75rem',
            lineHeight: '2.1rem',
        },
    },
    'subtitle1': {
        'fontFamily': 'Canela-Black',
        'fontSize': '1.5625rem',
        'fontStyle': 'normal',
        'fontWeight': 900,
        'lineHeight': 'normal',
        '@media screen and (max-width:1024px)': {
            fontSize: '1.4375rem',
            lineHeight: '1.725rem',
        },
    },
    'subtitle2': {
        'fontFamily': 'Canela-Black',
        'fontSize': '1.25rem',
        'fontStyle': 'normal',
        'fontWeight': 900,
        'lineHeight': 'normal',
        '@media screen and (max-width:1024px)': {
            fontSize: '1.1875rem',
            lineHeight: '1.425rem',
        },
    },
    'subtitle2bold': {
        'fontFamily': 'Canela-Black',
        'fontSize': '1.25rem',
        'fontStyle': 'normal',
        'fontWeight': 900,
        'lineHeight': 'normal',
        '@media screen and (max-width:1024px)': {
            fontSize: '1.1875rem',
            lineHeight: '1.425rem',
        },
    },
    'paragraph': {
        fontFamily: 'Poppins',
        fontSize: '0.9375rem',
        fontStyle: 'normal',
        fontWeight: 400,
        lineHeight: 'normal',
    },
    'paragraph-bold': {
        fontFamily: 'Poppins-Medium',
        fontSize: '0.9375rem',
        fontStyle: 'normal',
        fontWeight: 500,
        lineHeight: 'normal',
    },
    'caption': {
        fontFamily: 'Poppins',
        fontSize: '0.8125rem',
        fontStyle: 'normal',
        fontWeight: 400,
        lineHeight: 'normal',
    },
    'caption-bold': {
        fontFamily: 'Poppins-Medium',
        fontSize: '0.8125rem',
        fontStyle: 'normal',
        fontWeight: 500,
        lineHeight: 'normal',
    },
    'caption-dark': {
        fontFamily: 'Poppins',
        fontSize: '0.8125rem',
        fontStyle: 'normal',
        fontWeight: 400,
        lineHeight: 'normal',
        color: '#00273a',
    },
    'caption-small': {
        fontFamily: 'Poppins',
        fontSize: '0.625rem',
        fontStyle: 'normal',
        fontWeight: 400,
        lineHeight: 'normal',
    },
    'caption-bold-small': {
        fontFamily: 'Poppins-Medium',
        fontSize: '0.625rem',
        fontStyle: 'normal',
        fontWeight: 500,
        lineHeight: 'normal',
    },
    'alt-display1': {
        'fontFamily': 'Poppins-SemiBold',
        'fontSize': '3.8125rem',
        'fontStyle': 'normal',
        'fontWeight': 600,
        'lineHeight': 'normal',
        '@media screen and (max-width:1024px)': {
            fontSize: '3rem',
            lineHeight: '3.6rem',
        },
    },
    'alt-display2': {
        'fontFamily': 'Poppins-SemiBold',
        'fontSize': '3.0625rem',
        'fontStyle': 'normal',
        'fontWeight': 600,
        'lineHeight': 'normal',
        '@media screen and (max-width:1024px)': {
            fontSize: '2.5rem',
            lineHeight: '3rem',
        },
    },
    'alt-title1': {
        'fontFamily': 'Poppins-SemiBold',
        'fontSize': '2.4375rem',
        'fontStyle': 'normal',
        'fontWeight': 600,
        'lineHeight': 'normal',
        '@media screen and (max-width:1024px)': {
            fontSize: '2.0625rem',
            lineHeight: '2.475rem',
        },
    },
    'alt-title2': {
        'fontFamily': 'Poppins-SemiBold',
        'fontSize': '1.9375rem',
        'fontStyle': 'normal',
        'fontWeight': 600,
        'lineHeight': 'normal',
        '@media screen and (max-width:1024px)': {
            fontSize: '1.75rem',
            lineHeight: '2.1rem',
        },
    },
    'alt-subtitle1': {
        'fontFamily': 'Poppins-SemiBold',
        'fontSize': '1.5625rem',
        'fontStyle': 'normal',
        'fontWeight': 600,
        'lineHeight': 'normal',
        '@media screen and (max-width:1024px)': {
            fontSize: '1.4375rem',
            lineHeight: '1.725rem',
        },
    },
    'alt-subtitle2': {
        'fontFamily': 'Poppins-SemiBold',
        'fontSize': '1.25rem',
        'fontStyle': 'normal',
        'fontWeight': 600,
        'lineHeight': 'normal',
        '@media screen and (max-width:1024px)': {
            fontSize: '1.1875rem',
            lineHeight: '1.425rem',
        },
    },
    'btn-label': {
        fontFamily: 'Poppins-Medium',
        fontSize: '0.9375em',
        fontStyle: 'normal',
        lineHeight: 'normal',
        textTransform: 'capitalize',
    },
    'btn-label-small': {
        fontFamily: 'Poppins-Medium',
        fontSize: '0.8125rem',
        fontStyle: 'normal',
        lineHeight: 'normal',
        textTransform: 'capitalize',
    },
};
